/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "surface-tint": "#396844",
        "on-secondary-fixed-variant": "#005312",
        "tertiary": "#422800",
        "on-error-container": "#93000a",
        "secondary": "#1b6d24",
        "background": "#f9f9f8",
        "primary": "#023616",
        "outline-variant": "#c1c9be",
        "on-surface-variant": "#414941",
        "surface-container-high": "#e8e8e7",
        "on-secondary-fixed": "#002204",
        "surface-container-highest": "#e2e2e2",
        "secondary-container": "#a0f399",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2f3130",
        "on-tertiary-fixed-variant": "#643f00",
        "inverse-on-surface": "#f1f1f0",
        "on-primary-container": "#8bbd92",
        "secondary-fixed": "#a3f69c",
        "tertiary-container": "#603c00",
        "surface-bright": "#f9f9f8",
        "surface-dim": "#dadad9",
        "tertiary-fixed": "#ffddb5",
        "inverse-primary": "#a0d3a6",
        "outline": "#717970",
        "surface-container-low": "#f3f4f3",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeed",
        "on-surface": "#1a1c1c",
        "secondary-fixed-dim": "#88d982",
        "on-tertiary-fixed": "#2a1800",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb957",
        "primary-fixed-dim": "#a0d3a6",
        "surface": "#f9f9f8",
        "on-primary": "#ffffff",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#f0a01b",
        "on-primary-fixed-variant": "#21502e",
        "primary-container": "#1e4d2b",
        "on-primary-fixed": "#00210b",
        "error": "#ba1a1a",
        "on-secondary-container": "#217128",
        "on-error": "#ffffff",
        "primary-fixed": "#bbefc1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "grid-margin": "1.5rem",
        "grid-gutter": "1rem"
      },
      fontFamily: {
        sans: ["plusJakartaSans", "system-ui", "-apple-system", "sans-serif"],
        body: ["plusJakartaSans", "sans-serif"],
        headline: ["plusJakartaSans", "sans-serif"],
        "body-sm": ["plusJakartaSans"],
        "label-md": ["plusJakartaSans"],
        "headline-md": ["plusJakartaSans"],
        "headline-lg": ["plusJakartaSans"],
        "label-lg": ["plusJakartaSans"],
        "headline-xl-mobile": ["plusJakartaSans"],
        "headline-xl": ["plusJakartaSans"],
        "body-md": ["plusJakartaSans"],
        "label-sm": ["plusJakartaSans"],
        "headline-lg-mobile": ["plusJakartaSans"],
        "body-lg": ["plusJakartaSans"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
